### ISSUE TITLE
Service's 

### ISSUE THREAD

**Issue by Teamolduser** [viralvaghela/OSINT_MOBILE#1]
Please add more services like phonepe paytm Google pay freecharge mobikwik e.t.c online services like phone pe red buss irctc and e.t.c

**Comment by viralvaghela** [comment]
Hi @Teamolduser , Thanks for the feedback, I am already working on it, added a few of them, and will push new updates soon! 
Thanks

**Comment by Teamolduser** [comment]
Thanks for adding it bro and and thanks bro
